### ISSUE TITLE
Code for running on TUM VI

### ISSUE THREAD

**Issue by IslamAAli** [kk9six/duet#2]
Hello, 

I can only see the main code for the euroC dataset, would you mind sharing the code for TUM VI or point out if they are different in some sense 

Thanks

**Comment by kk9six** [comment]
Hi Islam,

i just uploaded the code for tumvi. basically, you just need to load the tumvicali or tumviuncali dataset instead of euroc dataset. then remove the AVE metric.
i also fixed a load error in dataset.py for tumvicali and tumviuncali. please check.

Best regards

**Comment by IslamAAli** [comment]
Hello, 

Thanks a lot .. I will give it a try and let you know how it goes.

BTW, what do you mean by tumvicali and tumviuncali ? which sequences would each group include ?

**Comment by IslamAAli** [comment]
Hello again, 

I ran the code on the uncalib TUMVI data, and the following are the results (I used my network for separate nets)

 => test dataset-room1_512_16...
Absolute Orientation Error (AOE): 79.24928283691406
Absolute Yaw Error (AYE): 29.47689437866211
Relative Translation Error (RTE): 7.264646053314209
Improvement of Relative Translation Error (RAW, DUET, Improvement): (6.7989507, 2.7077203, 0.5315844)

 => test dataset-room3_512_16...
Absolute Orientation Error (AOE): 103.2440185546875
Absolute Yaw Error (AYE): 57.02421951293945
Relative Translation Error (RTE): 7.588629722595215
Improvement of Relative Translation Error (RAW, DUET, Improvement): (7.8997064, 3.4489734, 0.590029)

 => test dataset-room5_512_16...
Absolute Orientation Error (AOE): 90.73448944091797
Absolute Yaw Error (AYE): 65.88880157470703
Relative Translation Error (RTE): 8.536825180053711
Improvement of Relative Translation Error (RAW, DUET, Improvement): (8.140417, 4.0959883, 0.52964026)

 => test dataset-room2_512_16...
Absolute Orientation Error (AOE): 119.81531524658203
Absolute Yaw Error (AYE): 70.67034149169922
Relative Translation Error (RTE): 6.853376388549805
Improvement of Relative Translation Error (RAW, DUET, Improvement): (6.791378, 2.1158059, 0.714666)

 => test dataset-room4_512_16...
Absolute Orientation Error (AOE): 66.31298828125
Absolute Yaw Error (AYE): 39.26103973388672
Relative Translation Error (RTE): 8.860584259033203
Improvement of Relative Translation Error (RAW, DUET, Improvement): (9.163455, 3.510291, 0.63431853)

 => test dataset-room6_512_16...
Absolute Orientation Error (AOE): 107.61212158203125
Absolute Yaw Error (AYE): 94.91608428955078
Relative Translation Error (RTE): 8.342419624328613
Improvement of Relative Translation Error (RAW, DUET, Improvement): (8.288776, 2.6690109, 0.68409485)

I believe the orientation error is huge, any suggestion on why this is happening? 

Thanks

**Comment by IslamAAli** [comment]
Hello, 

I tested the TUM-VI with my separate net branch, and the following are the results for room sequences:

 => test dataset-room1_512_16...
Absolute Orientation Error (AOE): 5.949290752410889
Absolute Yaw Error (AYE): 4.59436559677124
Relative Translation Error (RTE): 0.46432626247406006
Improvement of Relative Translation Error (RAW, DUET, Improvement): (0.4822704, 0.42196122, 0.16752607)

 => test dataset-room3_512_16...
Absolute Orientation Error (AOE): 6.709928512573242
Absolute Yaw Error (AYE): 6.372497081756592
Relative Translation Error (RTE): 0.5478178858757019
Improvement of Relative Translation Error (RAW, DUET, Improvement): (0.57361937, 0.5416157, 0.089916565)

 => test dataset-room5_512_16...
Absolute Orientation Error (AOE): 5.170485019683838
Absolute Yaw Error (AYE): 4.423435688018799
Relative Translation Error (RTE): 0.5481849312782288
Improvement of Relative Translation Error (RAW, DUET, Improvement): (0.5365811, 0.52084786, 0.041683313)

 => test dataset-room2_512_16...
Absolute Orientation Error (AOE): 25.644180297851562
Absolute Yaw Error (AYE): 25.12124252319336
Relative Translation Error (RTE): 0.6453423500061035
Improvement of Relative Translation Error (RAW, DUET, Improvement): (0.5114507, 0.4523706, 0.15784195)

 => test dataset-room4_512_16...
Absolute Orientation Error (AOE): 3.3426198959350586
Absolute Yaw Error (AYE): 1.8617761135101318
Relative Translation Error (RTE): 0.485514760017395
Improvement of Relative Translation Error (RAW, DUET, Improvement): (0.6062025, 0.5986884, -0.008127001)

 => test dataset-room6_512_16...
Absolute Orientation Error (AOE): 15.312334060668945
Absolute Yaw Error (AYE): 14.591169357299805
Relative Translation Error (RTE): 0.547336757183075
Improvement of Relative Translation Error (RAW, DUET, Improvement): (0.59031564, 0.6287557, -0.09649047)

I believe that the data from the dataset is the calib data, and the uncali data is some sort of synethesized data? is that correct? 

Thanks,
islam

**Comment by kk9six** [comment]
Hi Islam,

tumvicali is the original tumvi dataset. in the dataset, the IMU was strictly calibrated using the global optimization method.
tumviuncali is the synthesized uncalibrated data given the calibrated parameters.

**Comment by IslamAAli** [comment]
Thanks .. I think I got it working fine now.
